### ISSUE TITLE
Audio Issue in game when viewing an NDI in OBS

### ISSUE THREAD

**Issue by Mattabase** [Rushmead/MC-NDI#2]
Fabric version 1.19.2/3 both have this issue

Forge Version 1.19.2/3 will test shortly 

Seems that whenever I am connected to an NDI source in OBS my MC audio gets really messed up, almost like the audio for each cam is playing back in game, It happens with audio on off for the NDI source in OBS

I have not checked if this only occurs in with OBS will testing other sources when I can.

**Comment by Rushmead** [comment]
Ah found this! It appears for some reason it was constantly updating who the current audio source was, I've now patched this. New versions for Fabric & Forge 1.19.3 are on Modrinth and will be on CurseForge soon. 1.19.2 build I'll put in discord
